apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8200
      protocol: TCP
  selector:
    app: vault
